---
title: "Thresholding dialectometry [Diareg-GTRP overlap] 25-1-2021"
author: "Raoul Buurke"
date: "1/25/2021"
output: 
    html_document:
      theme: sandstone
      highlight: pygments
      toc: true
      df_print: paged
      code_folding: show
      toc_float: 
          collapsed: true
          smooth_scroll: true
      number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, cache = FALSE)
```

# Load libs + import data
```{r}
library(readr)
library(mgcv)
library(itsadug)

# df_gtrp <- read_delim("~/Leven/threshold/gtrp_diareg_overlap_simulation_norm_mat_diff.txt", 
#     "\t", escape_double = FALSE, trim_ws = TRUE)
# df_diareg_om <- read_delim("DOWNLOADS/pdf/PHD/Leven/threshold/diareg_om_gtrp_overlap_simulation_norm_mat_diff.txt", 
#     "\t", escape_double = FALSE, trim_ws = TRUE)
df_diareg_om <- read_delim("PHD/Leven/threshold/diareg_om_gtrp_overlap_simulation.txt", 
                                                "\t", escape_double = FALSE, trim_ws = TRUE)
df_gtrp <- read_delim("DOWNLOADS/pdf/PHD/Leven/threshold/diareg_om_gtrp_overlap_simulation.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)
```


# Plot influence of sample sizes: GTRP (Diareg overlap)
```{r}
# different location sample sizes
m1 = gam(corr ~ s(loc_ssize), data =  df_gtrp)
plot(m1, shade = T, rug = T, main='GTRP (overlapping DiaReg locations)', xlab = 'Number of locations', ylab = 'Normalized matrix difference')
abline(h=0)

boxplot(df_diareg_om$corr ~ df_diareg_om$word_ssize)
boxplot(df_diareg_om$corr ~ df_diareg_om$loc_ssize)


# different word sample sizes
m2 = gam(corr ~ s(word_ssize), data =  df_gtrp)
plot(m2, shade = T, rug = T, main='GTRP (overlapping DiaReg locations)', xlab = 'Number of words', ylab = 'Normalized matrix difference')
abline(h=0)
```

# Plot influence of sample sizes: DiaReg
```{r}
# different location sample sizes
m3 = gam(corr ~ s(loc_ssize), data =  df_diareg_om)
plot(m3, shade = T, rug = T, main='DiaReg', xlab = 'Number of locations', ylab = 'Normalized matrix difference')
abline(h=0)

# different word sample sizes
m4 = gam(corr ~ s(word_ssize), data =  df_diareg_om)
plot(m4, shade = T, rug = T, main='DiaReg', xlab = 'Number of words', ylab = 'Normalized matrix difference')
abline(h=0)
```


```{r}
ldf_20 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_linear_20_loc_81.txt", sep="")
plot(ldf_20$X.., main = '20 words, linear order', ylim = c(0,1))
ldf_40 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_linear_40_loc_81.txt", sep="")
plot(ldf_40$X.., main = '40 words, linear order', ylim = c(0,1))
ldf_60 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_linear_60_loc_81.txt", sep="")
plot(ldf_60$X.., main = '60 words, linear order', ylim = c(0,1))
ldf_80 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_linear_80_loc_81.txt", sep="")
plot(ldf_80$X.., main = '80 words, linear order', ylim = c(0,1))

df_20 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_20_loc_81.txt", sep="")
plot(df_20$X.., main = '20 words, random location samples', ylim = c(0,1))
df_40 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_40_loc_81.txt", sep="")
plot(df_40$X.., main = '40 words, random location samples', ylim = c(0,1))
df_60 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_60_loc_81.txt", sep="")
plot(df_60$X.., main = '60 words, random location samples', ylim = c(0,1))
df_80 = read.csv("~/Leven/threshold/matrices/diareg_om_gtrp/correlations_word_80_loc_81.txt", sep="")
plot(df_80$X.., main = '80 words, random location samples', ylim = c(0,1))

par(mfrow=c(2,2))

```

```{r}
df_diareg_om = read_delim("~/Leven/threshold/diareg_om_gtrp_overlap_simulation.txt", 
    "\t", escape_double = FALSE, trim_ws = TRUE)

boxplot(df_diareg_om$corr ~ df_diareg_om$loc_ssize)

m1 = gam(corr ~ s(loc_ssize) + s(word_ssize), data = df_diareg_om)
plot(m1)

m_mix = gam(corr ~ s(loc_ssize, word_ssize), data = df_diareg_om)

fvisgam(m_mix, view = c('loc_ssize', 'word_ssize'))

```

